<?php

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Check if BFIE_Admin class exists.
 */
if( !class_exists( 'BFIE_Admin' ) ) {

	/**
	 * The admin-specific functionality of the plugin.
	 *
	 * Handles admin menu registration, settings tabs, submenu items,
	 * notifications, settings display, and settings saving.
	 *
	 * @since 1.0.0
	 */
	class BFIE_Admin {

		/**
		 * Menu slug.
		 *
		 * @var string
		 */
		public $menu_slug = BFIE_MENU_SLUG;
		
		/**
		 * Settings key.
		 *
		 * @var string
		 */
		public $settings_key = 'bfie_setting_fields';

		/**
		 * Errors generated by the plugin.
		 *
		 * @var array
		 */
		private static $errors   = array();

		/**
		 * Messages generated by the plugin.
		 *
		 * @var array
		 */
		private static $messages   = array();

		/**
		 * Initialize the class and set its properties.
		 *
		 * Registers the hooks required for the admin functionality.
		 *
		 * @since 1.0.0
		 */
		public function __construct() {

			add_action( 'admin_menu', array( $this, 'register_admin_menu' ) );
			add_action( 'admin_init', array( $this, 'save' ) );
		}

		/**
		 * Add a message for the plugin.
		 *
		 * @since 1.0.0
		 *
		 * @param string $text Message text.
		 * @return void
		 */
		public static function add_message( $text ) {

			self::$messages[] = $text;
		}

		/**
		 * Add an error for the plugin.
		 *
		 * @since 1.0.0
		 *
		 * @param string $text Error text.
		 * @return void
		 */
		public static function add_error( $text ) {
			self::$errors[] = $text;
		}

		/**
		 * Get plugin messages.
		 *
		 * @since 1.0.0
		 *
		 * @return array Plugin messages.
		 */
		public static function get_messages() {
			return self::$messages;
		}

		/**
		 * Get plugin errors.
		 *
		 * @since 1.0.0
		 *
		 * @return array Plugin errors.
		 */
		public static function get_errors() {
			return self::$errors;
		}

		/**
		 * Register the admin menu.
		 *
		 * @since 1.0.0
		 *
		 * @return void
		 */
		public function register_admin_menu() {

			add_menu_page(
				__( 'Bulk Featured Image', 'bulk-featured-image' ),
				__( 'BFI','bulk-featured-image' ),
				'manage_options',
				$this->menu_slug,
				array($this,'process_admin_menu'),
				'dashicons-hourglass'
			);
		}

		/**
		 * Get the current admin page.
		 *
		 * @since 1.0.0
		 *
		 * @return string Current admin page slug.
		 */
		public function current_page() {
			return !empty( $_REQUEST['page'] ) ? sanitize_text_field( $_REQUEST['page'] ) : '';
		}

		/**
		 * Get the current admin section.
		 *
		 * @since 1.0.0
		 *
		 * @return string Current section slug.
		 */
		public function current_section() {
			
			$current_section = $this->current_page();
			$current_menu = '';

			if( !empty($current_section) && $current_section == $this->menu_slug ) {
				$current_menu = !empty( $_REQUEST['tab'] ) ? sanitize_text_field( $_REQUEST['tab'] ) : '';
			}

			return $current_menu;
		}

		/**
		 * Get the current subsection.
		 *
		 * @since 1.0.0
		 *
		 * @return string Current subsection slug.
		 */
		public function current_sub_section() {
			
			$bfi_get_settings = bfi_get_settings( 'general');
            $menu_items = !empty( $bfi_get_settings['bfi_posttyps'] ) ? $bfi_get_settings['bfi_posttyps'] : '';
            $sub_section = !empty( $_REQUEST['section'] ) ? sanitize_text_field( $_REQUEST['section'] ) : '';
			
			if( empty($sub_section)) {
				$sub_section = !empty( $menu_items[0] ) ? $menu_items[0] : '';
			}

			return $sub_section;
		}

		/**
		 * Get the main menu items.
		 *
		 * @since 1.0.0
		 *
		 * @return array Admin menu items.
		 */
		public function menu_items() {

			return apply_filters( 'bfie_menu_items', array(
				'' => __( 'General', 'bulk-featured-image' ),
				'post_types' => __( 'PostTypes', 'bulk-featured-image' ),
				'uninstall' => __( 'Uninstall', 'bulk-featured-image' ),
			) );
		}

		/**
		 * Display the main admin menu.
		 *
		 * @since 1.0.0
		 *
		 * @return void
		 */
		public function menu() {
			$menu_items = $this->menu_items();
			if ( empty( $menu_items ) || ! is_array( $menu_items ) ) {
				return;
			}

			$current_section = $this->current_section();
			$base_link       = admin_url( 'admin.php?page=' . $this->menu_slug );
			?>
			<nav class="bfi-tabs">
				<?php foreach ( $menu_items as $key => $menu ) : 
					$menu_link = $base_link;
					if ( ! empty( $key ) ) {
						$menu_link .= '&tab=' . $key;
					}

					$active = '';
					if ( ! empty( $current_section ) && $key == $current_section ) {
						$active = 'bfi-tabs__link--active';
					} elseif ( empty( $current_section ) && strtolower( $menu ) == 'general' ) {
						$active = 'bfi-tabs__link--active';
					}
					?>
					<a href="<?php echo esc_url( $menu_link ); ?>" class="bfi-tabs__link <?php echo esc_attr( $active ); ?>">
						<?php echo esc_html( $menu ); ?>
					</a>
				<?php endforeach; ?>

				<a href="<?php echo esc_url( 'https://store.creedally.com/product/bulk-featured-image-pro/' ); ?>" target="_blank" rel="nofollow" class="bfi-tabs__upgrade">
					<img src="<?php echo esc_url( BFIE_PLUGIN_URL . '/assets/images/icon-upgrade-pro.svg' ); ?>" alt="Upgrade" />
					<span><?php _e( 'Upgrade to Pro', 'bulk-featured-image' ); ?></span>
				</a>
			</nav>
			<?php
		}

		/**
		 * Get submenu items.
		 *
		 * @since 1.0.0
		 *
		 * @return array Submenu items.
		 */
		public function sub_menu_items() {

			$submenu_items = array(
				'general' => array(),
			);

			$bfi_get_settings = bfi_get_settings( 'general');
			$submenu_items['post_types'] = !empty($bfi_get_settings['bfi_posttyps']) ? $bfi_get_settings['bfi_posttyps'] : '';

			return apply_filters( 'bfie_submenu_items', $submenu_items );
		}

		/**
		 * Display submenu items.
		 *
		 * @since 1.0.0
		 *
		 * @return void
		 */
		public function sub_menu() {
			$sub_menu_items  = $this->sub_menu_items();
			$current_section = $this->current_section();
			$section         = ! empty( $current_section ) ? $current_section : 'general';
			$menu_link = admin_url( 'admin.php?page=' . $this->menu_slug );

			if ( ! empty( $current_section ) ) {
				$menu_link .= '&tab=' . $current_section;
			}

			$menu_items = ! empty( $sub_menu_items[ $section ] ) ? $sub_menu_items[ $section ] : array();
			$bfi_get_settings       = bfi_get_settings( 'general' );
			$enable_default_image   = ! empty( $bfi_get_settings['enable_default_image'] ) && is_array( $bfi_get_settings['enable_default_image'] ) ? $bfi_get_settings['enable_default_image'] : array();

			if ( ! empty( $menu_items ) && is_array( $menu_items ) ) {
				$menu_items = array_filter(
					$menu_items,
					function ( $menu_item ) use ( $enable_default_image ) {
						$menu_item = sanitize_text_field( $menu_item );
						return in_array( $menu_item, $enable_default_image, true );
					}
				);
			}

			$sub_section = ! empty( $_REQUEST['section'] ) ? sanitize_text_field( $_REQUEST['section'] ) : '';
			if ( empty( $sub_section ) ) {
				$sub_section = ! empty( $menu_items[0] ) ? $menu_items[0] : '';
			}

			if ( ! empty( $menu_items ) && is_array( $menu_items ) ) {
				?>
				<div class="bfi-submenu-wrap">
					<nav class="bfi-pills-nav">
						<?php foreach ( $menu_items as $menu_item ) {
							$active_class = ( ! empty( $menu_item ) && $menu_item === $sub_section ) ? 'is-active' : '';
							?>
								<a href="<?php echo esc_url( $menu_link . '&section=' . $menu_item ); ?>" class="bfi-pill-item <?php echo esc_attr( $active_class ); ?>" > <?php echo esc_html( ucfirst( $menu_item ) ); ?> </a>
							<?php
						} ?>
					</nav>
				</div>
				<?php
			}
		}

		/**
		 * Display the admin heading title.
		 *
		 * @since 1.0.0
		 *
		 * @return void
		 */
		public function heading_title() {

			$menu_items = $this->menu_items();
			$current_section = $this->current_section();

			$heading_title = !empty( $menu_items[$current_section] ) ? sanitize_text_field( $menu_items[$current_section] ).' '.__('Settings','bulk-featured-image') : '';
			?>
			<h1 class="wp-heading-inline"><?php echo apply_filters( 'bfie_heading_title',$heading_title,$current_section); ?></h1>
			<?php

		}

		/**
		 * Display plugin notifications.
		 *
		 * @since 1.0.0
		 *
		 * @return void
		 */
		public function notification() {
			?>
			<div class="bfi-notification-wrap">
                <?php
                if ( sizeof( self::$errors ) > 0 ) {
	                foreach ( self::$errors as $error ) {
		                echo '<div id="message" class="error inline notice is-dismissible"><p>' . $error . '</p></div>';
	                }
                } elseif ( sizeof( self::$messages ) > 0 ) {
	                foreach ( self::$messages as $message ) {
		                echo '<div id="message" class="updated inline notice is-dismissible"><p>' . $message . '</p></div>';
	                }
                }
                ?>
            </div>
			<?php
		}

		/**
		 * Process the admin BFI settings page.
		 *
		 * @since 1.0.0
		 *
		 * @return void
		 */
		public function process_admin_menu() {
			$current_page        = $this->current_page();
			$current_section     = $this->current_section();
			$current_sub_section = $this->current_sub_section();
			?>
			<div class="wrap bfi-admin-wrap">
				<div class="bfi-settings-layout">
					<div class="bfi-header">
						<?php $section_label = $current_section ? str_replace( '_', ' ', $current_section ) : 'General'; $section_label = ucwords( $section_label ); ?>
						<div class="bfi-header__breadcrumb"> <?php echo esc_html__( 'BFIE', 'bulk-featured-image' ); ?> / <?php echo esc_html( $section_label ); ?> <?php echo esc_html__( 'Settings', 'bulk-featured-image' ); ?> </div>
						<h1 class="bfi-header__title"> <?php echo esc_html( $section_label ); ?> Settings </h1>
						<p class="bfi-header__subtitle"><?php _e( 'Control how BFIE lists, imports, and displays your content.', 'bulk-featured-image' ); ?></p>
					</div>

					<?php $this->menu(); ?>
					<?php $this->sub_menu(); ?>

					<div class="bfi-notice bfi-notice--info">
						<span class="bfi-notice__icon">ⓘ</span>
						<span class="bfi-notice__text"><?php _e( 'Changes apply site-wide the next time a list is rendered. Existing cached lists refresh automatically.', 'bulk-featured-image' ); ?></span>
					</div>

					<form method="post" id="bfie_form_main" action="" enctype="multipart/form-data">
						<div class="bfi-content-wrap">
							<?php
							do_action( 'bfie_section_before_content', $current_section );
							do_action( 'bfie_section_content', $current_section );

							$section = '_general';
							if ( ! empty( $current_section ) ) {
								$section = '_' . strtolower( $current_section );
							}

							do_action( 'bfie_section_content' . $section, $current_section );
							do_action( 'bfie_section_after_content', $current_section );
							?>
						</div>

						<div class="bfi-actions">
							<button name="save" class="button button-primary" type="submit" value="Save changes"><?php _e( 'Save changes', 'bulk-featured-image' ); ?></button>
							<input type="hidden" name="action" value="bfi_form_action">
							<input type="hidden" name="_nonce" value="<?php echo esc_attr( wp_create_nonce( 'bfie_form_main' ) ); ?>">
							<input type="hidden" name="current_page" value="<?php echo esc_attr( $current_page ); ?>">
							<input type="hidden" name="current_section" value="<?php echo esc_attr( $current_section ); ?>">
							<input type="hidden" name="current_sub_section" value="<?php echo esc_attr( $current_sub_section ); ?>">
						</div>
					</form>
				</div>
			</div>      
			<?php
		}

		/**
		 * Get the redirect URL for the current section.
		 *
		 * @since 1.0.0
		 *
		 * @return string Redirect URL.
		 */
		public function redirect_url() {

			$current_section = !empty( $_POST['current_section'] ) ? sanitize_text_field( $_POST['current_section'] ) : '';
			$menu_link = admin_url( 'admin.php?page='.$this->menu_slug);

			if( !empty($current_section)) {
				$menu_link .='&tab='.$current_section;
			}

			return $menu_link;
		}

		/**
		 * Save BFI settings.
		 *
		 * Validates the submitted form action and nonce before saving
		 * the submitted settings.
		 *
		 * @since 1.0.0
		 *
		 * @return void
		 */
		public function save() {

			if( isset( $_POST['action'] ) && !empty( sanitize_text_field( $_POST['action'] ) ) && sanitize_text_field( $_POST['action'] )  == 'bfi_form_action' ) {
				if( isset( $_POST['_nonce'] ) && !empty( $_POST['_nonce'] ) && wp_verify_nonce( sanitize_text_field( $_POST['_nonce'] ), 'bfie_form_main' ) ) {					
					$current_section = !empty( $_POST['current_section'] ) ? sanitize_text_field( $_POST['current_section'] ) : 'general';
				
					if( has_action( 'bfie_save_section_'.$current_section ) ) {
						do_action('bfie_save_section_'.$current_section);
						return true;
					}

					$settings = bfi_sanitize_text_field($_POST);
					unset($settings['save']);
					unset($settings['action']);
					unset($settings['_nonce']);
					unset($settings['current_page']);
					unset($settings['current_section']);
					unset($settings['current_sub_section']);
		            
					$setting_key = 'bfi_settings';
					$bfi_settings = get_option( $setting_key, true );

					if( !empty( $bfi_settings ) && is_array( $bfi_settings ) ) {
			            $bfi_settings[$current_section] = $settings;
		            } else{
			            $bfi_settings = array(
				            $current_section =>  $settings,
                        );
                    }

		            update_option( $setting_key, $bfi_settings );

					self::add_message( __( 'Your settings have been saved.', 'bulk-featured-image' ) );
				} else {
					self::add_error( __( 'Something went wrong. settings nonce not verified.', 'bulk-featured-image' ) );
				}
			}
		}
	}

	new BFIE_Admin();
}
